module.exports = {
  en: {
    home: "Home",
    posts: "Posts",
    feed: "Feed",
    previous: "Previous",
    next: "Next",
    builtWith: "Built with",
  },
  es: {
    home: "Inicio",
    posts: "Publicaciones",
    feed: "Feed",
    previous: "Anterior",
    next: "Siguiente",
    builtWith: "Construido con",
  },
  fr: {
    home: "Accueil",
    posts: "Publications",
    feed: "Feed",
    previous: "Précédent",
    next: "Suivant",
    builtWith: "Construit avec",
  },
  ko: {
    home: "홈",
    posts: "게시물",
    feed: "피드",
    previous: "이전",
    next: "다음",
    builtWith: "에 기반하여 구축됨",
  },
  ms: {
    home: "Halaman Utama",
    posts: "Posts",
    feed: "Feed",
    previous: "Sebelumnya",
    next: "Seterusnya",
    builtWith: "Dibina dengan",
  },
  pt: {
    home: "Início",
    posts: "Posts",
    feed: "Feed",
    previous: "Anterior",
    next: "Próximo",
    builtWith: "Construido com",
  },
  zh: {
    home: "主页",
    posts: "帖子",
    feed: "订阅源",
    previous: "上一篇",
    next: "下一篇",
    builtWith: "搭建于",
  },
  ja: {
    home: "ホーム",
    posts: "投稿",
    feed: "フィード",
    previous: "先",
    next: "次",
    builtWith: "で構築",
  },
};
